### ISSUE TITLE
Typo in the paper for the categorical distribution w+ and w-?

### ISSUE THREAD

**Issue by arnauqb** [gaurav-arya/StochasticAD.jl#109]
Hi,

I'm looking at equations (A.13) and (A.14) of the [paper](https://arxiv.org/pdf/2210.08572.pdf). Isn't the sumation indices for $w_-$ and $w_+$ wrong? Looking at the [code](https://github.com/gaurav-arya/StochasticAD.jl/blob/2b98e1201f29e565db6a153bab523ef418fb0732/src/discrete_randomness.jl#L126), it seems to me it should be $$\sum_{i=1}^{x-1}$$ for $w_+$ and $$\sum_{i=x+1}^n$$ for $w_{-}$. 

Am I missing something? Thanks!

**Comment by gaurav-arya** [comment]
Hi! Apologies for the late reply, I'm just wrapping up my semester.

Since the probabilities sum to 1, the derivatives must sum to 0, and so `right_sum = -sum(δs[(val + 1):end], init = zero(V))` should be equivalent to `right_sum = left_sum + δs[val]`, which should more evidently match the expression in the paper. Now, `left_sum` is used in the weight of jumping to a previous element: 

https://github.com/gaurav-arya/StochasticAD.jl/blob/db4333c604cc23c3c36420f09aa998d01ef0214b/src/discrete_randomness.jl#L141

while `right_sum` is used in the weight of jumping to a following element: 

https://github.com/gaurav-arya/StochasticAD.jl/blob/db4333c604cc23c3c36420f09aa998d01ef0214b/src/discrete_randomness.jl#L155-L156

So I think this should match the paper, but feel free to correct me / seek further clarification!

**Comment by arnauqb** [comment]
Hi, apologies for the late answer, I missed the notification of your reply :)
Thank you for the clarification, this makes sense now!
