### ISSUE TITLE
exporting public API

### ISSUE THREAD

**Issue by GuusAvis** [gaurav-arya/StochasticAD.jl#127]
Hello!

I noticed that there are a couple of functions that are listed in the Public API documentation but that are not exported by `StochasticAD.jl`. Moreover, I think it would be useful if they were exported. These functions are
- `value`;
- `delta`.

Perhaps there is a good reason for not exporting them, but in case this is an oversight perhaps they can be added to the exports. Thanks!

**Comment by gaurav-arya** [comment]
Hi! Thanks for making the issue. In general, I think there's a practice in Julia to only export symbols that are unlikely to clash with other packages. I felt like `value` and `delta` were too generic to export, but they are indeed still public API. (On the other hand, there may be more specific identifiers that are not exported due to my oversight; feel free to open a new issue if you spot any of these.)

Julia 1.11 is going to get a `public` keyword to use in exactly this situation: once that's available, I'll definitely mark `value` and `delta` as `public`!

**Comment by GuusAvis** [comment]
That makes sense, thanks!
